In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import scipy.stats as stats
import matplotlib.pyplot as plt

In [2]:
update_prof = {'Episódico/Epidêmico':'Episodic/Epidemic', 'Epidêmico':'Epidemic', 'Episódico':'Episodic',
       'Transmissão Persistente':'Persistent Transmission', 'Sem transmissão': 'No Transmission', 'Sem transmissao': 'No Transmission'}
prof_order = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission']

Dataset com a população:

In [3]:
pop = pd.read_csv('../Determinantes/Tabelas/poptcu2010-2022new.csv', sep = ',', usecols= ['CODMUN7', 'POP22', 'POP10'])
#pop['populacao'] = pop['populacao'].astype(float)
pop.columns = pop.columns.str.lower()
pop.head()

   codmun7  pop22    pop10
0  1100015  21495  24392.0
1  1100023  96833  90353.0
2  1100031   5363   6313.0
3  1100049  86895  78574.0
4  1100056  15890  17029.0

Abrindo o dataframe com os perfis:

In [4]:
df_10_16 = pd.read_csv('../Determinantes/clima/clima_agg_10_16.csv', index_col = 'Unnamed: 0')

df_10_16.loc[:, 'dengue_pattern'] = df_10_16.dengue_pattern.replace(update_prof)

df_10_16['period'] = '10_16'

df_10_16 = df_10_16.merge(pop[['codmun7', 'pop10']], left_on = 'geocodigo', right_on = 'codmun7').drop('codmun7', axis = 1).rename(columns = {'pop10': 'pop'})

df_10_16.head()

,geocodigo,temp_med,umid_med,precip_tot,thr_temp,thr_umid,thr_prec,thr_temp_umid,year,dengue_pattern,period,pop
0,2700102,25.917411,71.160050,174.737289,364,314,2,314,2010,Episodic/Epidemic,10_16,19377.0
1,2700201,25.484200,80.407899,424.205669,364,364,5,364,2010,Episodic/Epidemic,10_16,17424.0
2,2700300,25.588142,77.216115,277.945870,364,364,2,364,2010,Epidemic,10_16,214006.0
3,2700409,24.897218,81.989589,423.138619,364,364,4,364,2010,Episodic/Epidemic,10_16,44322.0
4,2700508,25.800147,78.780638,491.421552,364,363,5,363,2010,Episodic,10_16,14230.0

In [5]:
df_10_16.isnull().sum()

geocodigo          0
temp_med           0
umid_med           0
precip_tot         0
thr_temp           0
thr_umid           0
thr_prec           0
thr_temp_umid      0
year               0
dengue_pattern     0
period             0
pop               35
dtype: int64

In [6]:
df_17_22 = pd.read_csv('../Determinantes/clima/clima_agg_17_22.csv', index_col = 'Unnamed: 0')

df_17_22 = df_17_22.merge(pop[['codmun7', 'pop22']], left_on = 'geocodigo', right_on = 'codmun7').drop('codmun7', axis = 1).rename(columns = {'pop22': 'pop'})

df_17_22.loc[:, 'dengue_pattern'] = df_17_22.dengue_pattern.replace(update_prof)

df_17_22['period'] = '17_22'

df_17_22.head()

,geocodigo,temp_med,umid_med,precip_tot,thr_temp,thr_umid,thr_prec,thr_temp_umid,year,dengue_pattern,pop,period
0,2700102,26.368572,65.759019,79.313571,371,241,0,241,2020,Episodic/Epidemic,19008,17_22
1,2700201,25.656351,78.530554,320.167782,371,371,3,371,2020,Episodic/Epidemic,13811,17_22
2,2700300,25.839300,73.983355,187.897610,371,366,1,366,2020,Epidemic,234696,17_22
3,2700409,25.007031,80.555151,336.263240,371,371,3,371,2020,Episodic,37512,17_22
4,2700508,25.844227,79.239810,418.317611,371,371,4,371,2020,Episodic,16365,17_22

In [8]:
df_17_22.isnull().sum()

geocodigo         0
temp_med          0
umid_med          0
precip_tot        0
thr_temp          0
thr_umid          0
thr_prec          0
thr_temp_umid     0
year              0
dengue_pattern    0
pop               0
period            0
dtype: int64

#### Tabela com as variáveis categóricas

Abrindo o dataframe com os perfis e fazendo o merge deles:

In [10]:
df_det = pd.read_csv('../Determinantes/Tabelas/transition10192022/banco_determinantes_fim.csv',encoding='latin-1', sep = ';')

for col in ['altitude', 'prop_esgot', 'prop_abast', 'prop_residuo']:
    df_det[col] = df_det[col].str.replace(',', '.').astype(float)

df_det.head()

,muni_code,muni_name,uf_code,uf_acr,tipo_regiao,bioma,altitude,koppen,pop22,prop_esgot,prop_abast,prop_residuo
0,1100015,Alta Floresta D'oeste,11,RO,não metropolitana,amazonia,246.08,Am,21558,2.24,93.68,56.86
1,1100023,Ariquemes,11,RO,não metropolitana,amazonia,165.90,Am,100896,8.91,98.57,85.14
2,1100031,Cabixi,11,RO,não metropolitana,amazonia,224.18,Am,5107,21.01,95.49,49.77
3,1100049,Cacoal,11,RO,metropolitana,amazonia,229.95,Am,92202,54.03,98.16,78.94
4,1100056,Cerejeiras,11,RO,não metropolitana,amazonia,192.22,Am,15237,16.73,98.62,78.35

In [11]:
df_perfis_10_16 = pd.read_csv('../Dengue/dengue_pattern_10_16.csv', sep = ';', usecols = ['muni_code',
                                                                                         'dengue_pattern'])

df_perfis_10_16.head()

   muni_code       dengue_pattern
0    1100015  Episódico/Epidêmico
1    1100023            Epidêmico
2    1100031  Episódico/Epidêmico
3    1100049            Epidêmico
4    1100056            Epidêmico

In [12]:
df_det_10_16 = df_det.merge(df_perfis_10_16, left_on='muni_code', right_on = 'muni_code')

df_det_10_16.loc[:, 'dengue_pattern'] = df_det_10_16.dengue_pattern.replace(update_prof)

df_det_10_16.head()

,muni_code,muni_name,uf_code,uf_acr,tipo_regiao,bioma,altitude,koppen,pop22,prop_esgot,prop_abast,prop_residuo,dengue_pattern
0,1100015,Alta Floresta D'oeste,11,RO,não metropolitana,amazonia,246.08,Am,21558,2.24,93.68,56.86,Episodic/Epidemic
1,1100023,Ariquemes,11,RO,não metropolitana,amazonia,165.90,Am,100896,8.91,98.57,85.14,Epidemic
2,1100031,Cabixi,11,RO,não metropolitana,amazonia,224.18,Am,5107,21.01,95.49,49.77,Episodic/Epidemic
3,1100049,Cacoal,11,RO,metropolitana,amazonia,229.95,Am,92202,54.03,98.16,78.94,Epidemic
4,1100056,Cerejeiras,11,RO,não metropolitana,amazonia,192.22,Am,15237,16.73,98.62,78.35,Epidemic

In [14]:
df_perfis_17_22 = pd.read_csv('../Dengue/dengue_pattern_17_22.csv', sep = ';', usecols = ['muni_code',
                                                                                         'dengue_pattern'])
df_perfis_17_22 = df_perfis_17_22.dropna()
df_perfis_17_22.loc[:, 'muni_code'] = df_perfis_17_22['muni_code'].astype(int)
df_perfis_17_22.head()

   muni_code       dengue_pattern
0    1100015            Epidêmico
1    1100023            Epidêmico
2    1100031  Episódico/Epidêmico
3    1100049            Epidêmico
4    1100056  Episódico/Epidêmico

In [15]:
df_det_17_22 = df_det.merge(df_perfis_17_22 , left_on='muni_code', right_on = 'muni_code')

df_det_17_22.loc[:, 'dengue_pattern'] = df_det_17_22.dengue_pattern.replace(update_prof)

df_det_17_22.head()

,muni_code,muni_name,uf_code,uf_acr,tipo_regiao,bioma,altitude,koppen,pop22,prop_esgot,prop_abast,prop_residuo,dengue_pattern
0,1100015,Alta Floresta D'oeste,11,RO,não metropolitana,amazonia,246.08,Am,21558,2.24,93.68,56.86,Epidemic
1,1100023,Ariquemes,11,RO,não metropolitana,amazonia,165.90,Am,100896,8.91,98.57,85.14,Epidemic
2,1100031,Cabixi,11,RO,não metropolitana,amazonia,224.18,Am,5107,21.01,95.49,49.77,Episodic/Epidemic
3,1100049,Cacoal,11,RO,metropolitana,amazonia,229.95,Am,92202,54.03,98.16,78.94,Epidemic
4,1100056,Cerejeiras,11,RO,não metropolitana,amazonia,192.22,Am,15237,16.73,98.62,78.35,Episodic/Epidemic

Criando o cabeçario da tabela com o número de municípios em cada uma das classes:

In [17]:
df_cab_10_16 = pd.DataFrame(df_det_10_16.dengue_pattern.value_counts()).T

df_cab_10_16 = df_cab_10_16[prof_order]

df_cab_10_16

dengue_pattern,No Transmission,Episodic,Episodic/Epidemic,Epidemic,Persistent Transmission
count,286,1722,2907,642,13

In [18]:
df_cab_17_22 = pd.DataFrame(df_det_17_22.dengue_pattern.value_counts()).T

df_cab_17_22 = df_cab_17_22[prof_order]

df_cab_17_22

dengue_pattern,No Transmission,Episodic,Episodic/Epidemic,Epidemic,Persistent Transmission
count,150,1841,2821,726,32

Aplicando o test chi2 na tabela com o bioma:

c_table_bioma_count = pd.crosstab(df_det['bioma'], df_det['dengue_pattern'])[prof_order]

chi2, p, _, _f = stats.chi2_contingency(c_table_bioma_count)

# calculando a frequência 
c_table_bioma_freq = (100*(c_table_bioma_count/df_cab.values[0])).round(2)

# somando como string a contagem e frequências para atingir o formato desejado 
c_table_bioma_end = c_table_bioma_count.astype(str) + ' (' + c_table_bioma_freq.astype(str) + ')'

# adicionando informações extras na tabela: 
c_table_bioma_end['type'] = 'bioma'

c_table_bioma_end['p-value'] = p

c_table_bioma_end

Aplicando o teste chi2 na tabela dos tipos climáticos:

c_table_tipo_count = pd.crosstab(df_det['koppen'], df_det['dengue_pattern'])

chi2, p, _, _f = stats.chi2_contingency(c_table_tipo_count)

c_table_tipo_freq = (100*(c_table_tipo_count/df_cab.values[0])).round(2)

c_table_tipo_end = c_table_tipo_count.astype(str) + ' (' + c_table_tipo_freq.astype(str) + ')'

c_table_tipo_end['type'] = 'tipos climáticos'

c_table_tipo_end['p-value'] = p


c_table_tipo_end

df_cab['type'] = ''
df_cab['p-value'] = ''

Gerando a tabela final concatenando os cabeçarios e os tipos climático:

df_end_cat = pd.concat([df_cab, c_table_bioma_end, c_table_tipo_end])

df_end_cat.to_csv('../Determinantes/Tabelas/summary_categoric_py.csv')

df_end_cat

Analisando as colunas dos datasets com os dados climáticos:

In [19]:
col = 'thr_temp_umid'

In [21]:
stats.ttest_ind(df_10_16.loc[df_10_16.dengue_pattern == prof_order[0]][col].values, 
             df_10_16.loc[df_10_16.dengue_pattern == prof_order[1]][col].values)

TtestResult(statistic=-27.132966413962922, pvalue=4.591883485299935e-158, df=14054.0)

In [22]:
stats.ttest_ind(df_10_16.loc[df_10_16.dengue_pattern == prof_order[1]][col].values, 
             df_10_16.loc[df_10_16.dengue_pattern == prof_order[2]][col].values)

TtestResult(statistic=-38.21640559076422, pvalue=0.0, df=32401.0)

In [23]:
stats.ttest_ind(df_10_16.loc[df_10_16.dengue_pattern == prof_order[2]][col].values, 
             df_10_16.loc[df_10_16.dengue_pattern == prof_order[3]][col].values)

TtestResult(statistic=-10.582255296544119, pvalue=4.093944107266934e-26, df=24841.0)

In [24]:
stats.ttest_ind(df_10_16.loc[df_10_16.dengue_pattern == prof_order[3]][col].values, 
             df_10_16.loc[df_10_16.dengue_pattern == prof_order[4]][col].values)

TtestResult(statistic=2.0068088469202285, pvalue=0.04482864820501286, df=4583.0)

In [26]:

def mean_std(df, col = 'temp_med'):
    '''
    Essa função retorna a media e desvio padrão no formato de string para cada um dos grupos, 
    além do nome da coluna utilizada e do p-valor obtido no teste anova 
    '''
    
    no_trans = df.loc[df.dengue_pattern == 'No Transmission'][col].values
    
    epis = df.loc[df.dengue_pattern == 'Episodic'][col].values
    
    epis_epid = df.loc[df.dengue_pattern == 'Episodic/Epidemic'][col].values
    
    epid = df.loc[df.dengue_pattern == 'Epidemic'][col].values
    
    per_trans = df.loc[df.dengue_pattern ==  'Persistent Transmission'][col].values
    
    f_stat, p = stats.f_oneway(no_trans, epis, epis_epid, epid, per_trans)

    return [f'{round(np.mean(no_trans),2)} ({round(np.std(no_trans),2)})',
           f'{round(np.mean(epis),2)} ({round(np.std(epis),2)})',
           f'{round(np.mean(epis_epid),2)} ({round(np.std(epis_epid),2)})',
           f'{round(np.mean(epid),2)} ({round(np.std(epid),2)})',
           f'{round(np.mean(per_trans),2)} ({round(np.std(per_trans),2)})',
            col, p, f'{round(np.mean(df[col].values),2)} ({round(np.std(df[col].values),2)})']

# o método abaixo contatena os valores obtidos pela função mean_std no formato de um dataframe com o valor obtido para todas as variáveis 
# numéricas 

num_values = pd.concat([pd.DataFrame([mean_std(df_10_16, col = 'temp_med')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                            pd.DataFrame([mean_std(df_10_16, col = 'umid_med')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                            pd.DataFrame([mean_std(df_10_16, col = 'precip_tot')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std(df_det_10_16, col = 'altitude')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std(df_10_16.dropna(), col = 'pop')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std(df_det_10_16, col = 'prop_esgot')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value','global']),
                       pd.DataFrame([mean_std(df_det_10_16, col = 'prop_abast')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std(df_det_10_16, col = 'prop_residuo')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global'])],
                           ignore_index = True).set_index('column')


num_values

,No Transmission,Episodic,Episodic/Epidemic,Epidemic,Persistent Transmission,p-value,global
column,,,,,,,
temp_med,19.9 (3.22),22.72 (3.62),24.24 (2.47),24.17 (2.2),23.17 (2.37),0.000000e+00,23.54 (3.09)
umid_med,78.12 (6.16),74.77 (7.7),71.96 (7.01),73.42 (6.79),74.24 (5.68),0.000000e+00,73.32 (7.35)
precip_tot,582.23 (173.38),468.77 (207.21),392.75 (179.14),431.48 (179.59),466.56 (169.4),0.000000e+00,430.62 (194.25)
altitude,453.05 (304.39),473.82 (320.85),446.03 (263.4),412.58 (271.88),493.73 (330.12),9.064135e-05,451.24 (286.21)
pop,5410.54 (4632.37),10031.51 (10074.53),20373.61 (29702.39),127175.01 (226676.53),2393301.62 (2962776.65),0.000000e+00,34277.77 (203094.37)
prop_esgot,40.26 (25.92),36.21 (28.06),42.14 (32.2),58.94 (31.07),85.31 (13.42),3.055725e-59,42.25 (31.28)
prop_abast,85.18 (14.97),82.88 (16.21),86.03 (14.68),92.72 (9.53),98.33 (2.62),9.315633e-46,85.82 (14.98)
prop_residuo,65.08 (23.61),62.95 (23.38),71.25 (20.05),86.5 (14.1),99.23 (0.65),5.790207e-133,70.19 (21.94)

In [27]:
df_end_num = pd.concat([df_cab_10_16, num_values])

df_end_num.to_csv('../Determinantes/Tabelas/10-16/summary_numeric_10_16.csv')

df_end_num

,No Transmission,Episodic,Episodic/Epidemic,Epidemic,Persistent Transmission,p-value,global
count,286,1722,2907,642,13,NaN,NaN
temp_med,19.9 (3.22),22.72 (3.62),24.24 (2.47),24.17 (2.2),23.17 (2.37),0.000000e+00,23.54 (3.09)
umid_med,78.12 (6.16),74.77 (7.7),71.96 (7.01),73.42 (6.79),74.24 (5.68),0.000000e+00,73.32 (7.35)
precip_tot,582.23 (173.38),468.77 (207.21),392.75 (179.14),431.48 (179.59),466.56 (169.4),0.000000e+00,430.62 (194.25)
altitude,453.05 (304.39),473.82 (320.85),446.03 (263.4),412.58 (271.88),493.73 (330.12),9.064135e-05,451.24 (286.21)
pop,5410.54 (4632.37),10031.51 (10074.53),20373.61 (29702.39),127175.01 (226676.53),2393301.62 (2962776.65),0.000000e+00,34277.77 (203094.37)
prop_esgot,40.26 (25.92),36.21 (28.06),42.14 (32.2),58.94 (31.07),85.31 (13.42),3.055725e-59,42.25 (31.28)
prop_abast,85.18 (14.97),82.88 (16.21),86.03 (14.68),92.72 (9.53),98.33 (2.62),9.315633e-46,85.82 (14.98)
prop_residuo,65.08 (23.61),62.95 (23.38),71.25 (20.05),86.5 (14.1),99.23 (0.65),5.790207e-133,70.19 (21.94)

Replicando a analise para o período 17_22

In [28]:

num_values_17_22 = pd.concat([pd.DataFrame([mean_std(df_17_22, col = 'temp_med')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                            pd.DataFrame([mean_std(df_17_22, col = 'umid_med')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                            pd.DataFrame([mean_std(df_17_22, col = 'precip_tot')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std(df_det_17_22, col = 'altitude')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std(df_17_22, col = 'pop')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std(df_det_17_22, col = 'prop_esgot')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value','global']),
                       pd.DataFrame([mean_std(df_det_17_22, col = 'prop_abast')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std(df_det_17_22, col = 'prop_residuo')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global'])],
                           ignore_index = True).set_index('column')

In [29]:
df_end_num_17_22 = pd.concat([df_cab_17_22, num_values_17_22])

df_end_num_17_22.to_csv('../Determinantes/Tabelas/17-22/summary_numeric_17_22.csv')

df_end_num_17_22

,No Transmission,Episodic,Episodic/Epidemic,Epidemic,Persistent Transmission,p-value,global
count,150,1841,2821,726,32,NaN,NaN
temp_med,20.47 (4.15),22.74 (3.67),23.64 (2.59),23.38 (2.11),22.63 (1.9),4.243958e-147,23.22 (3.05)
umid_med,77.52 (5.98),74.55 (6.65),71.71 (6.93),70.99 (7.17),70.97 (6.91),1.941979e-197,72.71 (7.04)
precip_tot,531.67 (181.52),435.71 (173.82),388.03 (158.79),408.03 (146.82),414.98 (101.04),2.249399e-114,410.42 (165.45)
altitude,510.35 (381.48),430.79 (314.76),458.83 (267.63),458.44 (249.2),518.04 (319.33),4.982657e-04,451.24 (286.21)
pop,5437.23 (4413.53),10259.54 (10221.22),21923.68 (32173.1),109949.78 (192834.53),1302777.34 (2166239.85),0.000000e+00,36456.47 (206498.48)
prop_esgot,36.23 (25.45),34.96 (27.4),41.9 (31.7),61.4 (31.04),85.83 (14.67),7.318017e-98,42.25 (31.28)
prop_abast,82.07 (14.04),82.1 (16.01),86.02 (14.85),94.61 (7.09),98.99 (1.04),4.867943e-88,85.82 (14.98)
prop_residuo,59.88 (25.85),61.74 (22.89),71.34 (19.75),88.04 (12.1),98.77 (1.17),5.861637e-198,70.19 (21.94)

Aplicar os resultados para o dataset the transição:

In [32]:
df_perfis_trans = pd.read_csv('../Determinantes/Dengue/transicao_new.csv', sep = ';', usecols = ['muni_code',
                                                                                         'transition'])

df_perfis_trans.head()

   muni_code  transition
0    1100015      Piorou
1    1100023  Se manteve
2    1100031  Se manteve
3    1100049  Se manteve
4    1100056    Melhorou

In [33]:
df_det_trans = df_det.merge(df_perfis_trans , left_on='muni_code', right_on = 'muni_code')

df_det_trans.head()

,muni_code,muni_name,uf_code,uf_acr,tipo_regiao,bioma,altitude,koppen,pop22,prop_esgot,prop_abast,prop_residuo,transition
0,1100015,Alta Floresta D'oeste,11,RO,não metropolitana,amazonia,246.08,Am,21558,2.24,93.68,56.86,Piorou
1,1100023,Ariquemes,11,RO,não metropolitana,amazonia,165.90,Am,100896,8.91,98.57,85.14,Se manteve
2,1100031,Cabixi,11,RO,não metropolitana,amazonia,224.18,Am,5107,21.01,95.49,49.77,Se manteve
3,1100049,Cacoal,11,RO,metropolitana,amazonia,229.95,Am,92202,54.03,98.16,78.94,Se manteve
4,1100056,Cerejeiras,11,RO,não metropolitana,amazonia,192.22,Am,15237,16.73,98.62,78.35,Melhorou

In [34]:
order = ['Melhorou', 'Se manteve', 'Piorou']

In [36]:
df_cab_trans  = pd.DataFrame(df_det_trans.transition.value_counts()).T[order]

df_cab_trans.head()

transition  Melhorou  Se manteve  Piorou
count            704        3893     973

In [37]:
df_clima_trans = df_17_22.merge(df_perfis_trans, left_on = 'geocodigo', right_on = 'muni_code').drop('muni_code', axis =1)

df_clima_trans

,geocodigo,temp_med,umid_med,precip_tot,thr_temp,thr_umid,thr_prec,thr_temp_umid,year,dengue_pattern,pop,period,transition
0,2700102,26.368572,65.759019,79.313571,371,241,0,241,2020,Episodic/Epidemic,19008,17_22,Se manteve
1,2700201,25.656351,78.530554,320.167782,371,371,3,371,2020,Episodic/Epidemic,13811,17_22,Se manteve
2,2700300,25.839300,73.983355,187.897610,371,366,1,366,2020,Epidemic,234696,17_22,Se manteve
3,2700409,25.007031,80.555151,336.263240,371,371,3,371,2020,Episodic,37512,17_22,Melhorou
4,2700508,25.844227,79.239810,418.317611,371,371,4,371,2020,Episodic,16365,17_22,Se manteve
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16705,4128625,19.109252,76.501094,529.897908,170,333,7,149,2022,Episodic/Epidemic,3055,17_22,Piorou
16706,4128633,18.029923,81.826031,571.521186,121,358,8,116,2022,No Transmission,5697,17_22,Melhorou
16707,4128658,18.867481,77.616679,533.025667,155,347,6,147,2022,Episodic,3811,17_22,Se manteve
16708,4128708,18.878705,76.664205,598.036250,160,336,12,143,2022,Episodic,9706,17_22,Se manteve
16709,4128807,22.825647,70.126035,453.607443,299,296,7,240,2022,Episodic/Epidemic,5798,17_22,Se manteve

In [40]:
def mean_std_trans(df, col = 'temp_med'):
    '''
    Essa função retorna a media e desvio padrão no formato de string para cada um dos grupos, 
    além do nome da coluna utilizada e do p-valor obtido no teste anova 
    '''
    
    mel = df.loc[df.transition == 'Melhorou'][col].values
    
    man = df.loc[df.transition == 'Se manteve'][col].values
    
    pio = df.loc[df.transition == 'Piorou'][col].values
    
    f_stat, p = stats.f_oneway(mel, man, pio)

    return [f'{round(np.mean(mel),2)} ({round(np.std(mel),2)})',
           f'{round(np.mean(man),2)} ({round(np.std(man),2)})',
           f'{round(np.mean(pio),2)} ({round(np.std(pio),2)})',
            col, p, f'{round(np.mean(df[col].values),2)} ({round(np.std(df[col].values),2)})']

In [41]:
num_values_trans = pd.concat([pd.DataFrame([mean_std_trans(df_clima_trans, col = 'temp_med')], columns = ['Melhorou', 'Se manteve', 'Piorou', 'column', 'p-value', 'global']),
                            pd.DataFrame([mean_std_trans(df_clima_trans, col = 'umid_med')], columns = ['Melhorou', 'Se manteve', 'Piorou', 'column', 'p-value', 'global']),
                            pd.DataFrame([mean_std_trans(df_clima_trans, col = 'precip_tot')], columns = ['Melhorou', 'Se manteve', 'Piorou', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std_trans(df_det_trans, col = 'altitude')], columns = ['Melhorou', 'Se manteve', 'Piorou', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std_trans(df_clima_trans, col = 'pop')], columns = ['Melhorou', 'Se manteve', 'Piorou', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std_trans(df_det_trans, col = 'prop_esgot')], columns = ['Melhorou', 'Se manteve', 'Piorou', 'column', 'p-value','global']),
                       pd.DataFrame([mean_std_trans(df_det_trans, col = 'prop_abast')], columns = ['Melhorou', 'Se manteve', 'Piorou', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std_trans(df_det_trans, col = 'prop_residuo')], columns = ['Melhorou', 'Se manteve', 'Piorou', 'column', 'p-value', 'global'])],
                           ignore_index = True).set_index('column')

In [43]:
df_end_num_trans = pd.concat([df_cab_trans, num_values_trans])

df_end_num_trans.to_csv('../Determinantes/Tabelas/transition10161722/summary_numeric_transition.csv')

df_end_num_trans

,Melhorou,Se manteve,Piorou,p-value,global
count,704,3893,973,NaN,NaN
temp_med,24.68 (2.76),23.26 (3.0),22.02 (2.96),2.702211e-211,23.22 (3.05)
umid_med,74.31 (7.11),72.34 (7.01),73.01 (6.91),5.960420e-33,72.71 (7.04)
precip_tot,409.04 (205.58),404.58 (160.17),434.8 (150.82),9.990671e-18,410.42 (165.45)
altitude,344.8 (279.57),465.87 (289.31),469.68 (260.93),3.454396e-25,451.24 (286.21)
pop,29792.26 (100394.17),38631.41 (233435.1),32576.22 (136829.29),1.040519e-01,36456.47 (206498.48)
prop_esgot,33.55 (28.02),43.18 (31.54),44.8 (31.46),8.984545e-15,42.25 (31.28)
prop_abast,80.9 (15.65),86.28 (14.56),87.49 (15.39),8.235506e-21,85.82 (14.98)
prop_residuo,63.91 (21.44),70.67 (21.96),72.82 (21.36),8.437756e-17,70.19 (21.94)

### Organize by region