In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import scipy.stats as stats
import matplotlib.pyplot as plt

In [2]:
update_prof = {'Episódico/Epidêmico':'Episodic/Epidemic', 'Epidêmico':'Epidemic', 'Episódico':'Episodic',
       'Transmissão Persistente':'Persistent Transmission', 'Sem transmissão': 'No Transmission', 'Sem transmissao': 'No Transmission'}
prof_order = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission']

Dataset com a população:

In [3]:
pop = pd.read_csv('../Determinantes/Tabelas/poptcu2010-2022new.csv', sep = ',', usecols= ['CODMUN7', 'POP22', 'POP10'])
#pop['populacao'] = pop['populacao'].astype(float)
pop.columns = pop.columns.str.lower()
pop.head()

   codmun7  pop22    pop10
0  1100015  21495  24392.0
1  1100023  96833  90353.0
2  1100031   5363   6313.0
3  1100049  86895  78574.0
4  1100056  15890  17029.0

Abrindo o dataframe com os perfis:

In [4]:
df_10_19 = pd.read_csv('../Determinantes/clima/clima_agg_10_19.csv', index_col = 'Unnamed: 0')

df_10_19.loc[:, 'dengue_pattern'] = df_10_19.dengue_pattern.replace(update_prof)

df_10_19['period'] = '10_19'

df_10_19 = df_10_19.merge(pop[['codmun7', 'pop10']], left_on = 'geocodigo', right_on = 'codmun7').drop('codmun7', axis = 1).rename(columns = {'pop10': 'pop'})

df_10_19.head()

,geocodigo,temp_med,umid_med,precip_tot,thr_temp,thr_umid,thr_prec,thr_temp_umid,year,dengue_pattern,period,pop
0,2700102,25.917411,71.160050,174.737289,364,314,2,314,2010,Episodic/Epidemic,10_19,19377.0
1,2700201,25.484200,80.407899,424.205669,364,364,5,364,2010,Episodic/Epidemic,10_19,17424.0
2,2700300,25.588142,77.216115,277.945870,364,364,2,364,2010,Epidemic,10_19,214006.0
3,2700409,24.897218,81.989589,423.138619,364,364,4,364,2010,Episodic/Epidemic,10_19,44322.0
4,2700508,25.800147,78.780638,491.421552,364,363,5,363,2010,Episodic,10_19,14230.0

In [5]:
df_10_19.isnull().sum()

geocodigo          0
temp_med           0
umid_med           0
precip_tot         0
thr_temp           0
thr_umid           0
thr_prec           0
thr_temp_umid      0
year               0
dengue_pattern     0
period             0
pop               50
dtype: int64

In [6]:
df_20_22 = pd.read_csv('../Determinantes/clima/clima_agg_20_22.csv', index_col = 'Unnamed: 0')

df_20_22 = df_20_22.merge(pop[['codmun7', 'pop22']], left_on = 'geocodigo', right_on = 'codmun7').drop('codmun7', axis = 1).rename(columns = {'pop22': 'pop'})

df_20_22.loc[:, 'dengue_pattern'] = df_20_22.dengue_pattern.replace(update_prof)

df_20_22['period'] = '20_22'

df_20_22.head()

,geocodigo,temp_med,umid_med,precip_tot,thr_temp,thr_umid,thr_prec,thr_temp_umid,year,dengue_pattern,pop,period
0,2700102,26.368572,65.759019,79.313571,371,241,0,241,2020,Episodic/Epidemic,19008,20_22
1,2700201,25.656351,78.530554,320.167782,371,371,3,371,2020,Episodic/Epidemic,13811,20_22
2,2700300,25.839300,73.983355,187.897610,371,366,1,366,2020,Epidemic,234696,20_22
3,2700409,25.007031,80.555151,336.263240,371,371,3,371,2020,Episodic/Epidemic,37512,20_22
4,2700508,25.844227,79.239810,418.317611,371,371,4,371,2020,Episodic,16365,20_22

In [7]:
df_20_22.isnull().sum()

geocodigo         0
temp_med          0
umid_med          0
precip_tot        0
thr_temp          0
thr_umid          0
thr_prec          0
thr_temp_umid     0
year              0
dengue_pattern    0
pop               0
period            0
dtype: int64

#### Tabela com as variáveis categóricas

Abrindo o dataframe com os perfis e fazendo o merge deles:

In [8]:
df_det = pd.read_csv('../Determinantes/Tabelas/banco_determinantes_fim.csv',encoding='latin-1', sep = ';')

for col in ['altitude', 'prop_esgot', 'prop_abast', 'prop_residuo']:
    df_det[col] = df_det[col].str.replace(',', '.').astype(float)

df_det.head()

,muni_code,muni_name,uf_code,uf_acr,tipo_regiao,bioma,altitude,koppen,pop22,prop_esgot,prop_abast,prop_residuo
0,1100015,Alta Floresta D'oeste,11,RO,não metropolitana,amazonia,246.08,Am,21558,2.24,93.68,56.86
1,1100023,Ariquemes,11,RO,não metropolitana,amazonia,165.90,Am,100896,8.91,98.57,85.14
2,1100031,Cabixi,11,RO,não metropolitana,amazonia,224.18,Am,5107,21.01,95.49,49.77
3,1100049,Cacoal,11,RO,metropolitana,amazonia,229.95,Am,92202,54.03,98.16,78.94
4,1100056,Cerejeiras,11,RO,não metropolitana,amazonia,192.22,Am,15237,16.73,98.62,78.35

In [9]:
df_perfis_10_19 = pd.read_csv('../Dengue/dengue_pattern_10_19.csv', sep = ';', usecols = ['muni_code',
                                                                                         'dengue_pattern'])

df_perfis_10_19.head()

   muni_code       dengue_pattern
0    1100015  Episódico/Epidêmico
1    1100023            Epidêmico
2    1100031  Episódico/Epidêmico
3    1100049            Epidêmico
4    1100056  Episódico/Epidêmico

In [10]:
df_det_10_19 = df_det.merge(df_perfis_10_19, left_on='muni_code', right_on = 'muni_code')

df_det_10_19.loc[:, 'dengue_pattern'] = df_det_10_19.dengue_pattern.replace(update_prof)

df_det_10_19.head()

,muni_code,muni_name,uf_code,uf_acr,tipo_regiao,bioma,altitude,koppen,pop22,prop_esgot,prop_abast,prop_residuo,dengue_pattern
0,1100015,Alta Floresta D'oeste,11,RO,não metropolitana,amazonia,246.08,Am,21558,2.24,93.68,56.86,Episodic/Epidemic
1,1100023,Ariquemes,11,RO,não metropolitana,amazonia,165.90,Am,100896,8.91,98.57,85.14,Epidemic
2,1100031,Cabixi,11,RO,não metropolitana,amazonia,224.18,Am,5107,21.01,95.49,49.77,Episodic/Epidemic
3,1100049,Cacoal,11,RO,metropolitana,amazonia,229.95,Am,92202,54.03,98.16,78.94,Epidemic
4,1100056,Cerejeiras,11,RO,não metropolitana,amazonia,192.22,Am,15237,16.73,98.62,78.35,Episodic/Epidemic

In [11]:
df_perfis_20_22 = pd.read_csv('../Dengue/dengue_pattern_20_22.csv', sep = ';', usecols = ['muni_code',
                                                                                         'dengue_pattern'])
df_perfis_20_22 = df_perfis_20_22.dropna()
df_perfis_20_22.loc[:, 'muni_code'] = df_perfis_20_22['muni_code'].astype(int)
df_perfis_20_22.head()

   muni_code       dengue_pattern
0  1100015.0            Epidêmico
2  1100023.0            Epidêmico
3  1100031.0  Episódico/Epidêmico
4  1100049.0            Epidêmico
5  1100056.0  Episódico/Epidêmico

In [12]:
df_det_20_22 = df_det.merge(df_perfis_20_22 , left_on='muni_code', right_on = 'muni_code')

df_det_20_22.loc[:, 'dengue_pattern'] = df_det_20_22.dengue_pattern.replace(update_prof)

df_det_20_22.head()

,muni_code,muni_name,uf_code,uf_acr,tipo_regiao,bioma,altitude,koppen,pop22,prop_esgot,prop_abast,prop_residuo,dengue_pattern
0,1100015,Alta Floresta D'oeste,11,RO,não metropolitana,amazonia,246.08,Am,21558,2.24,93.68,56.86,Epidemic
1,1100023,Ariquemes,11,RO,não metropolitana,amazonia,165.90,Am,100896,8.91,98.57,85.14,Epidemic
2,1100023,Ariquemes,11,RO,não metropolitana,amazonia,165.90,Am,100896,8.91,98.57,85.14,Epidemic
3,1100031,Cabixi,11,RO,não metropolitana,amazonia,224.18,Am,5107,21.01,95.49,49.77,Episodic/Epidemic
4,1100031,Cabixi,11,RO,não metropolitana,amazonia,224.18,Am,5107,21.01,95.49,49.77,Episodic/Epidemic

Criando o cabeçario da tabela com o número de municípios em cada uma das classes:

In [13]:
df_cab_10_19 = pd.DataFrame(df_det_10_19.dengue_pattern.value_counts()).T

df_cab_10_19 = df_cab_10_19[prof_order]

df_cab_10_19

dengue_pattern,No Transmission,Episodic,Episodic/Epidemic,Epidemic,Persistent Transmission
count,208,1780,2994,574,14

In [14]:
df_cab_20_22 = pd.DataFrame(df_det_20_22.dengue_pattern.value_counts()).T

df_cab_20_22 = df_cab_20_22[prof_order]

df_cab_20_22

dengue_pattern,No Transmission,Episodic,Episodic/Epidemic,Epidemic,Persistent Transmission
count,488,3350,5402,1821,78

Aplicando o test chi2 na tabela com o bioma:

c_table_bioma_count = pd.crosstab(df_det['bioma'], df_det['dengue_pattern'])[prof_order]

chi2, p, _, _f = stats.chi2_contingency(c_table_bioma_count)

# calculando a frequência 
c_table_bioma_freq = (100*(c_table_bioma_count/df_cab.values[0])).round(2)

# somando como string a contagem e frequências para atingir o formato desejado 
c_table_bioma_end = c_table_bioma_count.astype(str) + ' (' + c_table_bioma_freq.astype(str) + ')'

# adicionando informações extras na tabela: 
c_table_bioma_end['type'] = 'bioma'

c_table_bioma_end['p-value'] = p

c_table_bioma_end

Aplicando o teste chi2 na tabela dos tipos climáticos:

c_table_tipo_count = pd.crosstab(df_det['koppen'], df_det['dengue_pattern'])

chi2, p, _, _f = stats.chi2_contingency(c_table_tipo_count)

c_table_tipo_freq = (100*(c_table_tipo_count/df_cab.values[0])).round(2)

c_table_tipo_end = c_table_tipo_count.astype(str) + ' (' + c_table_tipo_freq.astype(str) + ')'

c_table_tipo_end['type'] = 'tipos climáticos'

c_table_tipo_end['p-value'] = p


c_table_tipo_end

df_cab['type'] = ''
df_cab['p-value'] = ''

Gerando a tabela final concatenando os cabeçarios e os tipos climático:

df_end_cat = pd.concat([df_cab, c_table_bioma_end, c_table_tipo_end])

df_end_cat.to_csv('../Determinantes/Tabelas/summary_categoric_py.csv')

df_end_cat

Analisando as colunas dos datasets com os dados climáticos:

In [15]:
col = 'thr_temp_umid'

In [16]:
stats.ttest_ind(df_10_19.loc[df_10_19.dengue_pattern == prof_order[0]][col].values, 
             df_10_19.loc[df_10_19.dengue_pattern == prof_order[1]][col].values)

TtestResult(statistic=-34.619962790602806, pvalue=4.563550160126075e-255, df=19878.0)

In [17]:
stats.ttest_ind(df_10_19.loc[df_10_19.dengue_pattern == prof_order[1]][col].values, 
             df_10_19.loc[df_10_19.dengue_pattern == prof_order[2]][col].values)

TtestResult(statistic=-43.198843078389636, pvalue=0.0, df=47738.0)

In [18]:
stats.ttest_ind(df_10_19.loc[df_10_19.dengue_pattern == prof_order[2]][col].values, 
             df_10_19.loc[df_10_19.dengue_pattern == prof_order[3]][col].values)

TtestResult(statistic=-6.5634073441377625, pvalue=5.3311543104991476e-11, df=35678.0)

In [19]:
stats.ttest_ind(df_10_19.loc[df_10_19.dengue_pattern == prof_order[3]][col].values, 
             df_10_19.loc[df_10_19.dengue_pattern == prof_order[4]][col].values)

TtestResult(statistic=4.05373455470679, pvalue=5.105735424260375e-05, df=5878.0)

In [20]:

def mean_std(df, col = 'temp_med'):
    '''
    Essa função retorna a media e desvio padrão no formato de string para cada um dos grupos, 
    além do nome da coluna utilizada e do p-valor obtido no teste anova 
    '''
    
    no_trans = df.loc[df.dengue_pattern == 'No Transmission'][col].values
    
    epis = df.loc[df.dengue_pattern == 'Episodic'][col].values
    
    epis_epid = df.loc[df.dengue_pattern == 'Episodic/Epidemic'][col].values
    
    epid = df.loc[df.dengue_pattern == 'Epidemic'][col].values
    
    per_trans = df.loc[df.dengue_pattern ==  'Persistent Transmission'][col].values
    
    f_stat, p = stats.f_oneway(no_trans, epis, epis_epid, epid, per_trans)

    return [f'{round(np.mean(no_trans),2)} ({round(np.std(no_trans),2)})',
           f'{round(np.mean(epis),2)} ({round(np.std(epis),2)})',
           f'{round(np.mean(epis_epid),2)} ({round(np.std(epis_epid),2)})',
           f'{round(np.mean(epid),2)} ({round(np.std(epid),2)})',
           f'{round(np.mean(per_trans),2)} ({round(np.std(per_trans),2)})',
            col, p, f'{round(np.mean(df[col].values),2)} ({round(np.std(df[col].values),2)})']

# o método abaixo contatena os valores obtidos pela função mean_std no formato de um dataframe com o valor obtido para todas as variáveis 
# numéricas 

num_values = pd.concat([pd.DataFrame([mean_std(df_10_19, col = 'temp_med')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                            pd.DataFrame([mean_std(df_10_19, col = 'umid_med')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                            pd.DataFrame([mean_std(df_10_19, col = 'precip_tot')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std(df_det_10_19, col = 'altitude')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std(df_10_19.dropna(), col = 'pop')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std(df_det_10_19, col = 'prop_esgot')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value','global']),
                       pd.DataFrame([mean_std(df_det_10_19, col = 'prop_abast')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std(df_det_10_19, col = 'prop_residuo')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global'])],
                           ignore_index = True).set_index('column')


num_values

,No Transmission,Episodic,Episodic/Epidemic,Epidemic,Persistent Transmission,p-value,global
column,,,,,,,
temp_med,19.46 (2.89),22.83 (3.65),24.22 (2.45),23.98 (2.13),22.74 (2.03),0.000000e+00,23.57 (3.05)
umid_med,78.28 (5.42),74.89 (7.44),72.01 (6.89),73.04 (6.8),72.63 (5.5),0.000000e+00,73.27 (7.2)
precip_tot,572.47 (150.48),465.97 (201.6),391.92 (171.95),429.25 (165.15),415.02 (82.14),0.000000e+00,426.23 (185.72)
altitude,483.08 (310.99),454.07 (322.61),449.65 (262.99),435.87 (269.47),586.15 (328.86),1.070640e-01,451.24 (286.21)
pop,4862.1 (3924.93),9890.89 (10138.56),20957.79 (30419.11),134472.83 (225442.4),2304225.43 (2900076.93),0.000000e+00,34277.77 (203094.37)
prop_esgot,41.52 (24.77),35.71 (28.05),42.16 (32.03),62.16 (30.04),87.2 (11.4),1.794015e-74,42.25 (31.28)
prop_abast,86.09 (12.97),82.39 (16.66),86.2 (14.39),94.0 (8.15),98.97 (0.89),2.441696e-60,85.82 (14.98)
prop_residuo,65.33 (23.12),62.3 (23.54),71.53 (19.78),88.74 (11.86),99.17 (0.67),4.233893e-157,70.19 (21.94)

In [21]:
df_end_num = pd.concat([df_cab_10_19, num_values])

df_end_num.to_csv('../Determinantes/Tabelas/10-19/summary_numeric_10_19.csv')

df_end_num

,No Transmission,Episodic,Episodic/Epidemic,Epidemic,Persistent Transmission,p-value,global
count,208,1780,2994,574,14,NaN,NaN
temp_med,19.46 (2.89),22.83 (3.65),24.22 (2.45),23.98 (2.13),22.74 (2.03),0.000000e+00,23.57 (3.05)
umid_med,78.28 (5.42),74.89 (7.44),72.01 (6.89),73.04 (6.8),72.63 (5.5),0.000000e+00,73.27 (7.2)
precip_tot,572.47 (150.48),465.97 (201.6),391.92 (171.95),429.25 (165.15),415.02 (82.14),0.000000e+00,426.23 (185.72)
altitude,483.08 (310.99),454.07 (322.61),449.65 (262.99),435.87 (269.47),586.15 (328.86),1.070640e-01,451.24 (286.21)
pop,4862.1 (3924.93),9890.89 (10138.56),20957.79 (30419.11),134472.83 (225442.4),2304225.43 (2900076.93),0.000000e+00,34277.77 (203094.37)
prop_esgot,41.52 (24.77),35.71 (28.05),42.16 (32.03),62.16 (30.04),87.2 (11.4),1.794015e-74,42.25 (31.28)
prop_abast,86.09 (12.97),82.39 (16.66),86.2 (14.39),94.0 (8.15),98.97 (0.89),2.441696e-60,85.82 (14.98)
prop_residuo,65.33 (23.12),62.3 (23.54),71.53 (19.78),88.74 (11.86),99.17 (0.67),4.233893e-157,70.19 (21.94)

Replicando a analise para o período 20_22

In [22]:

num_values_20_22 = pd.concat([pd.DataFrame([mean_std(df_20_22, col = 'temp_med')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                            pd.DataFrame([mean_std(df_20_22, col = 'umid_med')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                            pd.DataFrame([mean_std(df_20_22, col = 'precip_tot')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std(df_det_20_22, col = 'altitude')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std(df_20_22, col = 'pop')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std(df_det_20_22, col = 'prop_esgot')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value','global']),
                       pd.DataFrame([mean_std(df_det_20_22, col = 'prop_abast')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std(df_det_20_22, col = 'prop_residuo')], columns = ['No Transmission', 'Episodic', 'Episodic/Epidemic', 'Epidemic', 
       'Persistent Transmission', 'column', 'p-value', 'global'])],
                           ignore_index = True).set_index('column')

In [23]:
df_end_num_20_22 = pd.concat([df_cab_20_22, num_values_20_22])

df_end_num_20_22.to_csv('../Determinantes/Tabelas/20-22/summary_numeric_20_22.csv')

df_end_num_20_22

,No Transmission,Episodic,Episodic/Epidemic,Epidemic,Persistent Transmission,p-value,global
count,488,3350,5402,1821,78,NaN,NaN
temp_med,21.53 (4.2),22.96 (3.58),23.49 (2.76),23.37 (2.2),22.71 (2.22),5.209796e-72,23.22 (3.05)
umid_med,76.81 (6.39),74.05 (6.72),72.02 (6.96),71.17 (7.19),72.47 (6.87),1.151549e-139,72.71 (7.04)
precip_tot,512.22 (202.06),423.61 (171.04),390.98 (158.37),415.9 (153.58),425.56 (102.0),7.889131e-92,410.42 (165.45)
altitude,501.93 (393.47),438.12 (308.34),455.73 (271.48),447.86 (246.05),467.52 (321.82),7.260571e-05,451.25 (286.21)
pop,6764.84 (6389.57),10590.53 (11418.78),21023.23 (33195.53),88044.24 (162060.1),1196940.85 (1983633.88),0.000000e+00,36456.47 (206498.48)
prop_esgot,34.24 (25.35),34.98 (27.3),41.29 (31.42),58.89 (32.24),82.8 (16.03),2.263999e-193,42.25 (31.28)
prop_abast,80.76 (15.65),82.1 (15.81),85.82 (14.87),93.44 (9.66),98.35 (3.1),1.142137e-175,85.81 (14.98)
prop_residuo,60.37 (24.65),61.43 (22.56),70.82 (19.96),85.88 (14.63),98.43 (1.73),0.000000e+00,70.19 (21.94)

Aplicar os resultados para o dataset the transição:

In [24]:
df_perfis_trans = pd.read_csv('../Dengue/transicao.csv', sep = ';', usecols = ['muni_code',
                                                                                         'Transition'])

df_perfis_trans.head()

   muni_code  Transition
0    1100015      Piorou
1    1100023  Se manteve
2    1100031  Se manteve
3    1100049  Se manteve
4    1100056  Se manteve

In [25]:
df_det_trans = df_det.merge(df_perfis_trans , left_on='muni_code', right_on = 'muni_code')

df_det_trans.head()

,muni_code,muni_name,uf_code,uf_acr,tipo_regiao,bioma,altitude,koppen,pop22,prop_esgot,prop_abast,prop_residuo,Transition
0,1100015,Alta Floresta D'oeste,11,RO,não metropolitana,amazonia,246.08,Am,21558,2.24,93.68,56.86,Piorou
1,1100023,Ariquemes,11,RO,não metropolitana,amazonia,165.90,Am,100896,8.91,98.57,85.14,Se manteve
2,1100031,Cabixi,11,RO,não metropolitana,amazonia,224.18,Am,5107,21.01,95.49,49.77,Se manteve
3,1100049,Cacoal,11,RO,metropolitana,amazonia,229.95,Am,92202,54.03,98.16,78.94,Se manteve
4,1100056,Cerejeiras,11,RO,não metropolitana,amazonia,192.22,Am,15237,16.73,98.62,78.35,Se manteve

In [26]:
order = ['Melhorou', 'Se manteve', 'Piorou']

In [27]:
df_cab_trans  = pd.DataFrame(df_det_trans.Transition.value_counts()).T[order]

df_cab_trans.head()

Transition  Melhorou  Se manteve  Piorou
count            759        3648    1163

In [28]:
df_clima_trans = df_20_22.merge(df_perfis_trans, left_on = 'geocodigo', right_on = 'muni_code').drop('muni_code', axis =1)

df_clima_trans

,geocodigo,temp_med,umid_med,precip_tot,thr_temp,thr_umid,thr_prec,thr_temp_umid,year,dengue_pattern,pop,period,Transition
0,2700102,26.368572,65.759019,79.313571,371,241,0,241,2020,Episodic/Epidemic,19008,20_22,Se manteve
1,2700201,25.656351,78.530554,320.167782,371,371,3,371,2020,Episodic/Epidemic,13811,20_22,Se manteve
2,2700300,25.839300,73.983355,187.897610,371,366,1,366,2020,Epidemic,234696,20_22,Se manteve
3,2700409,25.007031,80.555151,336.263240,371,371,3,371,2020,Episodic/Epidemic,37512,20_22,Se manteve
4,2700508,25.844227,79.239810,418.317611,371,371,4,371,2020,Episodic,16365,20_22,Se manteve
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16705,4128625,19.109252,76.501094,529.897908,170,333,7,149,2022,Episodic/Epidemic,3055,20_22,Piorou
16706,4128633,18.029923,81.826031,571.521186,121,358,8,116,2022,No Transmission,5697,20_22,Melhorou
16707,4128658,18.867481,77.616679,533.025667,155,347,6,147,2022,Episodic/Epidemic,3811,20_22,Piorou
16708,4128708,18.878705,76.664205,598.036250,160,336,12,143,2022,Episodic/Epidemic,9706,20_22,Piorou
16709,4128807,22.825647,70.126035,453.607443,299,296,7,240,2022,Episodic/Epidemic,5798,20_22,Se manteve

In [29]:
def mean_std_trans(df, col = 'temp_med'):
    '''
    Essa função retorna a media e desvio padrão no formato de string para cada um dos grupos, 
    além do nome da coluna utilizada e do p-valor obtido no teste anova 
    '''
    
    mel = df.loc[df.Transition == 'Melhorou'][col].values
    
    man = df.loc[df.Transition == 'Se manteve'][col].values
    
    pio = df.loc[df.Transition == 'Piorou'][col].values
    
    f_stat, p = stats.f_oneway(mel, man, pio)

    return [f'{round(np.mean(mel),2)} ({round(np.std(mel),2)})',
           f'{round(np.mean(man),2)} ({round(np.std(man),2)})',
           f'{round(np.mean(pio),2)} ({round(np.std(pio),2)})',
            col, p, f'{round(np.mean(df[col].values),2)} ({round(np.std(df[col].values),2)})']

In [30]:
num_values_trans = pd.concat([pd.DataFrame([mean_std_trans(df_clima_trans, col = 'temp_med')], columns = ['Melhorou', 'Se manteve', 'Piorou', 'column', 'p-value', 'global']),
                            pd.DataFrame([mean_std_trans(df_clima_trans, col = 'umid_med')], columns = ['Melhorou', 'Se manteve', 'Piorou', 'column', 'p-value', 'global']),
                            pd.DataFrame([mean_std_trans(df_clima_trans, col = 'precip_tot')], columns = ['Melhorou', 'Se manteve', 'Piorou', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std_trans(df_det_trans, col = 'altitude')], columns = ['Melhorou', 'Se manteve', 'Piorou', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std_trans(df_clima_trans, col = 'pop')], columns = ['Melhorou', 'Se manteve', 'Piorou', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std_trans(df_det_trans, col = 'prop_esgot')], columns = ['Melhorou', 'Se manteve', 'Piorou', 'column', 'p-value','global']),
                       pd.DataFrame([mean_std_trans(df_det_trans, col = 'prop_abast')], columns = ['Melhorou', 'Se manteve', 'Piorou', 'column', 'p-value', 'global']),
                       pd.DataFrame([mean_std_trans(df_det_trans, col = 'prop_residuo')], columns = ['Melhorou', 'Se manteve', 'Piorou', 'column', 'p-value', 'global'])],
                           ignore_index = True).set_index('column')

In [31]:
df_end_num_trans = pd.concat([df_cab_trans, num_values_trans])

df_end_num_trans.to_csv('../Determinantes/Tabelas/transition/summary_numeric_transition.csv')

df_end_num_trans

,Melhorou,Se manteve,Piorou,p-value,global
count,759,3648,1163,NaN,NaN
temp_med,24.17 (2.91),23.33 (3.01),22.24 (3.01),1.340898e-131,23.22 (3.05)
umid_med,73.81 (7.11),72.3 (7.04),73.25 (6.87),2.380887e-25,72.71 (7.04)
precip_tot,406.61 (198.52),402.42 (160.59),438.01 (153.35),1.029765e-27,410.42 (165.45)
altitude,406.05 (305.45),464.41 (288.47),439.41 (261.52),5.887105e-07,451.24 (286.21)
pop,21961.58 (42758.87),40669.1 (247083.19),32702.31 (106434.33),2.104614e-04,36456.47 (206498.48)
prop_esgot,35.62 (27.86),42.38 (31.57),46.15 (31.8),4.014016e-12,42.25 (31.28)
prop_abast,81.78 (15.51),85.96 (14.65),87.99 (15.12),3.049226e-18,85.82 (14.98)
prop_residuo,64.74 (21.32),70.18 (22.05),73.8 (21.22),7.368406e-18,70.19 (21.94)